version: "3.8"

services:
  django:
    build: .
    container_name: teacher-student

    ports:
      - "8080:8000"
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#      sh -c "python manage.py makemigrations &&
#      python3 manage.py migrate &&
#      python3 manage.py runserver"